# Generated by Django 6.1.1 on 2026-09-27 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspeciePokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeapi_id', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo_primario', models.CharField(max_length=50)),
                ('tipo_secundario', models.CharField(blank=True, max_length=50, null=True)),
                ('hp_base', models.IntegerField()),
                ('ataque_base', models.IntegerField()),
                ('defesa_base', models.IntegerField()),
                ('ataque_especial_base', models.IntegerField()),
                ('defesa_especial_base', models.IntegerField()),
                ('velocidade_base', models.IntegerField()),
                ('sprite_url', models.URLField(blank=True, null=True)),
                ('capture_rate', models.IntegerField(default=255)),
                ('is_legendary', models.BooleanField(default=False)),
                ('is_mythical', models.BooleanField(default=False)),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('incomum', 'Incomum'), ('raro', 'Raro'), ('epico', 'Épico'), ('lendario', 'Lendário'), ('mitico', 'Mítico')], default='comum', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCapturado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.IntegerField(default=1)),
                ('data_captura', models.DateTimeField(auto_now_add=True)),
                ('iv_hp', models.IntegerField(default=0)),
                ('iv_ataque', models.IntegerField(default=0)),
                ('iv_defesa', models.IntegerField(default=0)),
                ('iv_ataque_especial', models.IntegerField(default=0)),
                ('iv_defesa_especial', models.IntegerField(default=0)),
                ('iv_velocidade', models.IntegerField(default=0)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.especiepokemon')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='jogadores.perfiljogador')),
            ],
        ),
    ]
