# Generated by Django 6.1.1 on 2026-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncapturado',
            name='evolucoes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
