# Generated by Django 6.1.1 on 2026-09-27 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemoncapturado_evolucoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokeapi_id', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('fisico', 'Físico'), ('especial', 'Especial'), ('status', 'Status')], max_length=20)),
                ('poder', models.IntegerField(blank=True, null=True)),
                ('precisao', models.IntegerField(blank=True, null=True)),
                ('pp', models.IntegerField(default=10)),
                ('prioridade', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pokemoncapturado',
            name='movimentos_atuais',
            field=models.ManyToManyField(blank=True, to='pokedex.move'),
        ),
        migrations.CreateModel(
            name='EspecieMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_aprendizado', models.IntegerField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_aprendiveis', to='pokedex.especiepokemon')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.move')),
            ],
            options={
                'unique_together': {('especie', 'movimento')},
            },
        ),
    ]
